CREATE TABLE QUESTIONS (

 QUESTION_ID SERIAL PRIMARY KEY,
 QID INTEGER,
 COMMUNITY varchar (100) NOT NULL,
 TAGS VARCHAR(500) [],
 CREATE_DATE TIMESTAMP,
 DURATION NUMERIC(10,2),
 PR_SCORE NUMERIC(10,3)
);
